excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - identifier_name
  - force_cast
  - force_try
  - todo
  