excluded:
  - iOS/Resources/Generated
  - iOS/Models/CoreData/Generated
  - iOS/Extras

# rules with explicit opt-in
opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  # - attributes # "Attributes should be on their own lines in functions and types, but on the same line as variables and imports"
  - balanced_xctest_lifecycle
  - blanket_disable_command
  - closure_body_length # default 20 lines
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
#  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
#  - convenience_type # "Types used for hosting only static members should be implemented as a caseless enum to avoid instantiation"
#  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
#  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
#  - explicit_acl
#  - explicit_enum_raw_value
  - explicit_init
#  - explicit_top_level_acl
#  - explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
#  - file_header # what is referenced `project pattern`?
#  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
#  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
#  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
#  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  # - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
#  - no_grouping_extension # extension should not be in the same file as main code
#  - no_magic_numbers
  - nslocalizedstring_key
#  - nslocalizedstring_require_bundle # "Calls to NSLocalizedString should specify the bundle which contains the strings file"
#  - number_separator
#  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
# - prefer_nimble
# - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
# - private_outlet
  - private_subject
# - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation # enforces type inference
#  - required_deinit
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
#  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
#  - superfluous_else
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
#  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
#  - vertical_whitespace_between_cases
#  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# rule identifiers to exclude from running
disabled_rules:
  - trailing_comma # collides with swiftformat
  - no_fallthrough_only # used with `@unknown default:` cases
  - identifier_name # 3 to 4O char names
  - type_name # 3 to 4O char names
  - function_parameter_count # 5 or less
  - line_length
  - type_body_length
  - force_cast
  - force_try
  - unused_closure_parameter
  - todo
  - superfluous_disable_command # when some rule is disabled, but affected code would not trigger it anyway

# rules config
empty_count:
  only_after_dot: true

file_length:
  warning: 400
  error: 800

function_body_length:
  warning: 75
  error: 150

large_tuple:
  warning: 4

implicit_return:
  included: [closure, getter]

indentation_width:
  include_comments: false
