excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Unapp/Google-Maps-iOS-Utils
  - Unapp/StyleKit.swift

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - identifier_name
  - trailing_whitespace
  - force_cast
  - force_try
  - unused_closure_parameter
  - todo
  