# paths to ignore during linting, takes precedence over `included`
excluded:
  - Pods

# rule identifiers to exclude from running
disabled_rules:
  - trailing_comma # enforced by swiftformat
  - no_fallthrough_only # used with `@unknown default:` cases
  - identifier_name # 3 to 4O char names
  - type_name # 3 to 4O char names
  - function_parameter_count # 5 or less
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - force_cast
  - force_try
  - unused_closure_parameter
  - todo
  