# rules with explicit opt-in
opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_body_length # default 20 lines
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
#  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - discouraged_optional_boolean
#  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
#  - explicit_acl
  - explicit_init
  - explicit_self
#  - explicit_top_level_acl
#  - extension_access_modifier
  - fatal_error_message
#  - file_header # what is referenced `project pattern`?
#  - file_name
  - first_where
#  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
#  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
#  - lower_acl_than_parent
#  - missing_docs
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
#  - no_grouping_extension # extension should not be in the same file as main code
  - nslocalizedstring_key
#  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
#  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
#  - private_action
#  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation # enforces type inference
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
#  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
#  - unavailable_function
  - unneeded_parentheses_in_closure_argumentuntyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
#  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# rule identifiers to exclude from running
disabled_rules:
  - trailing_comma # collides with swiftformat
  - no_fallthrough_only # used with `@unknown default:` cases
  - identifier_name # 3 to 4O char names
  - type_name # 3 to 4O char names
  - function_parameter_count # 5 or less
  - line_length
  - type_body_length
  - force_cast
  - force_try
  - unused_closure_parameter
  - todo

#rules config
file_length:
  warning: 500
  error: 2000

function_body_length:
  warning: 100
  error: 200

large_tuple:
  warning: 4
  error: 5

closure_body_length:
  warning: 25 # target: 20 (default value)
  error: 100
