# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.68.2"

default_platform :ios


lane :swift_lint do |options|
	output_file = "swiftlint.html"
	mode = :lint # :lint or :autocorrect
	swiftlint(
		mode: mode,
		reporter: "html",
		output_file: output_file,
		ignore_exit_status: true,
	)
	sh "open ../#{output_file}"
end

lane :swift_format do |options|
	sh "swiftformat ../menuol/**/*.swift --verbose --indent tab --self insert --disable unusedArguments"
end

desc "Run unit tests."
lane :unit_tests do
  run_tests(scheme: "menuol", code_coverage: true, thread_sanitizer: true, open_report: true)
end